ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v10.5.0'
    hooks:
      - id: eslint
        additional_dependencies:
            - "eslint"
            - "@eslint/js"
            - "globals"
        files: \.js?$
        types: [file]
        args:
        - --fix

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.17"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

